# name: Django CI CD


# on:

#   push:

#     branches:
#       - main



# jobs:


#  build-test:


#   runs-on: ubuntu-latest


#   steps:


#   - name: Checkout

#     uses: actions/checkout@v4



#   - name: Setup Python

#     uses: actions/setup-python@v5

#     with:

#       python-version: "3.11"



#   - name: Install packages

#     run:

#       pip install -r requirements.txt



#   - name: Django check

#     run:

#       python manage.py check



#   - name: Run tests

#     run:

#       python manage.py test



#   - name: Docker build

#     run:

#       docker build -t django-app .




#  deploy:


#   needs: build-test


#   runs-on: ubuntu-latest



#   steps:


#   - name: Deploy Render


#     run:

#       curl ${{ secrets.RENDER_DEPLOY_HOOK }}